- hosts: el7
  tasks:
  - name: configure audit syslog properties
    copy: src=audit/files/syslog.conf dest=/etc/audisp/plugins.d/syslog.conf mode=0640 owner=root group=root
  - name: configure base audit rules
    copy: src=audit/files/rules.d/ dest=/etc/audit/rules.d/ mode=0644 owner=root group=root
    notify:
      - reload auditd
  - name: generate privileged command rules
    script: audit/gen-priv-rules.sh
    args:
      creates: /etc/audit/rules.d/31-privileged.rules
    notify: 
      - reload auditd
  handlers:
    - name: reload auditd
      systemd: name=auditd state=reloaded
